---
title: "R Notebook"
output: html_notebook
group: 10
---

This is an R Markdown notebook for the data cleaning, engineering, and test visualization steps of our project.

## Setup

```{r}
library(tidyverse)
# Read the CSV file
data <- read.csv('Group_10_project/CrashData.csv')

# Drop unnecessary columns with missing data
columns_to_drop <- c('SPEED_DIFF_MAX', 'FUN', 'FAC', 'MPO_NAME', 'NODE', 'OFFSET', 'RNS_MP', 'OBJECTID', 'DOCUMENT_NBR', 'VSP', 'JURIS_CODE')
data <- data[, !(names(data) %in% columns_to_drop)]

# Drop rows with missing X or Y values
data <- data[complete.cases(data$X, data$Y), ]
```

```{r}
head(data)
```



## Data Prep for Plot 1

```{r}
unique(data$Physical.Juris.Name)
```

```{r}
# Convert Crash.Date to date format
data$Crash.Date <- mdy_hms(data$Crash.Date)

# Extract year and month
data <- mutate(data, MM_YYYY = format(Crash.Date, "%m-%Y"))
```

```{r}
library(dplyr)

# Group by Crash.Year and Physical.Juris.Name, and then aggregate by summing K_people and Persons_Injured, etc.
summarized_data <- data %>%
  group_by(MM_YYYY, Physical.Juris.Name) %>%
  summarise(
    K_people_sum = sum(K_People, na.rm = TRUE),
    Persons_Injured_sum = sum(Persons.Injured, na.rm = TRUE),
    Pedestrians_Killed_sum = sum(Pedestrians.Killed, na.rm = TRUE),
    Pedestrians_Injured_sum = sum(Pedestrians.Injured, na.rm = TRUE),
  )

```

```{r}
summarized_data
```

```{r}
write.csv(summarized_data, file = "plot_1_data.csv", row.names = FALSE)
```

#### Sample plot
```{r}
library(dplyr)
library(ggplot2)
library(lubridate)

# Assuming you have already defined "summarized_data"

arlington_data <- summarized_data %>%
  filter(Physical.Juris.Name == "000. Arlington County") %>%
  mutate(MM_YYYY = dmy(paste("01-", MM_YYYY, sep = ""))) %>% # Convert MM_YYYY to datetime format
  arrange(MM_YYYY) # Sort by MM_YYYY

# Plot a time series
ggplot(arlington_data) +
  geom_line(aes(x = MM_YYYY, y = Persons_Injured_sum, color = "Persons Injured")) +
  geom_line(aes(x = MM_YYYY, y = K_people_sum, color = "Persons Killed")) +
  scale_color_manual(values = c("Persons Injured" = "red", "Persons Killed" = "blue")) +
  labs(title = "Persons Injured Time Series in 000. Arlington County",
       x = "Date",
       y = "Persons Injured",
       color = "Outcome"
  ) +
  theme_minimal()

```

## Data Prep for Plot 2

```{r}
export_data <- data[, c("Crash.Severity", "Max.Speed.Diff", "Speed.", "Alcohol.", "Drowsy.", "Distracted.", "Weather.Condition", "Senior.", "Young.")]

export_data <- export_data %>%
  rename(Alcohol = `Alcohol.`) %>%
  rename(Drowsy = `Drowsy.`) %>%
  rename(Distracted = `Distracted.`)

write.csv(export_data, file = "plot_2_data.csv", row.names = FALSE)
```

## Data Prep for Plot 3

```{r}
export_data <- data[, c("x", "y", "Crash.Severity", "Physical.Juris.Name", "Crash.Military.Time", "Persons.Injured", "K_People", "Pedestrians.Injured", "Pedestrians.Killed", "Vehicle.Count", "Collision.Type", "Weather.Condition", "Light.Condition", "Roadway.Surface.Condition", "Roadway.Defect", "Roadway.Description", "Intersection.Type", "Alcohol.", "Unrestrained.", "Distracted.", "RTE.Name", "Crash.Date")]

export_data <- export_data %>%
  filter(Physical.Juris.Name == "104. City of Charlottesville")

# Export the selected columns to a CSV file
write.csv(export_data, file = "plot_3_data.csv", row.names = FALSE)
```

```{r}
export_data
```


```{r}
alc <- unique(data$Alcohol.)
alc
```

```{r}
belted <- unique(data$Unrestrained.)
belted
```

```{r}
Collision_Type <- unique(data$Collision.Type)
Collision_Type
```
```{r}
Weather_Condition <- unique(export_data$Weather.Condition)
Weather_Condition
```

```{r}
Light_Condition <- unique(export_data$Light.Condition)
Light_Condition
```

```{r}
Intersection_Type <- unique(export_data$Intersection.Type)
Intersection_Type
```

```{r}
Roadway_Surface_Condition <- unique(export_data$Roadway.Surface.Condition)
Roadway_Surface_Condition
```

```{r}
Roadway_Description <- unique(export_data$Roadway.Description)
Roadway_Description
```


```{r}
Roadway_Defect <- unique(export_data$Roadway.Defect)
Roadway_Defect
```


```{r}
min_value <- min(data$Crash.Military.Time)
max_value <- max(data$Crash.Military.Time)

print(min_value)
print(max_value)
```

## Other
```{r}
# Load the required library
library(ggplot2)

# Create the scatter plot
ggplot(data, aes(x = x, y = y, color = Crash.Severity)) +
  geom_point(size = 1) +
  labs(title = "Scatter Plot of X and Y colored by Crash Severity",
       x = "x",
       y = "y",
       color = "Crash Severity") +
  theme_minimal()

```

